- name: Listen vents on a webhook
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: 192.168.1.45
        port: 9092
        topic: my-topic
        group_id:
      filters: # testing 4 eda image
        - json_filter:
            include_keys: ['message', 'value']
        - dashes_to_underscores:
  rules:
    - name: say hello
      condition: event.body == "aa"
      action:
        run_job_template:
          name: "test-playbook"
          organization: "Default"
    - name: say goodbye and hello with worflow
      condition: event.body == "ee"
      action:
        run_workflow_template:
          name: "test-workflow"
          organization: "Default"
    - name: common action
      condition: "'ii' in event.body or 'oo' in event.body"
      action:
        run_job_template:
          name: "common-playbook" # awx/aap name job template for both conditions
          organization: "Default"