- name: Listen vents on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: say hello
      condition: event.payload.message == "Ansible is cool"
      action:
        run_job_template:
          name: "test-playbook" # awx/aap name job template
          organization: "Default"
        #run_playbook:
         # name: say-what.yml