- name: Listen vents on a webhook
  hosts: all
  sources:
    - name: webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
    #- ansible.eda.kafka:
     #   host: 192.168.1.45
      #  port: 9092
       # topic: my-topic
        # group_id:
      #filters: # testing 4 eda image
       # - json_filter:
        #    include_keys: ['message', 'value']
        #- dashes_to_underscores:
  rules:
    - name: say hello from job template
      condition: event.payload.message == "aa"
      action:
        run_job_template:
          name: "test-playbook"
          organization: "Default"
          # use ansible_eda when running on awx, is defualt variable 
          # that uses awx to get info from rulebook, this variable doesn't exist
          # when you run for exmaple run_Playbook, check more on 
          # the official docs https://ansible.readthedocs.io/projects/rulebook/en/stable/actions.html#run-job-template
          job_args:
            extra_vars:
              message_content: "{{ event.payload.message }}"
              payload_content: "{{ event.payload }}"
    - name: say hello from workflow template
      condition: event.payload.message == "uu"
      action:
        run_workflow_template:
          name: "test-workflow"
          organization: "Default"
          job_args:
            extra_vars:
              message_content: "{{ ansible_eda.payload.message }}"
              payload_content: "{{ ansible_eda.payload }}"

      #condition: "'a' in event.payload.message"
      #condition: event.payload.alerts[0].status == "firing" # para plugin de alertmanager
      #condition: event.payload.alerts[0].status == "firing" # con el ansible.eda.webhook
      #condition: event.body == "aa"
      #condition: event.payload.message == "aa" # postman
      #condition: event.payload.message > 3
