- name: Listen vents on a webhook
  hosts: all
  sources:
    - name: webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
    #- ansible.eda.kafka:
     #   host: 192.168.1.45
      #  port: 9092
       # topic: my-topic
        # group_id:
      #filters: # testing 4 eda image
       # - json_filter:
        #    include_keys: ['message', 'value']
        #- dashes_to_underscores:
  rules:
    - name: say hello
      condition: event.payload.message == "aa"
      action:
        run_job_template:
          name: "test-playbook"
          organization: "Default"
          extra_vars:
            message_content: "{{ event.payload.message }}"
    - name: say goodbye and hello with worflow
      condition: event.payload.message == "ee"
      action:
        run_workflow_template:
          name: "test-workflow"
          organization: "Default"

      #condition: "'a' in event.payload.message"
      #condition: event.payload.alerts[0].status == "firing" # para plugin de alertmanager
      #condition: event.payload.alerts[0].status == "firing" # con el ansible.eda.webhook
      #condition: event.body == "aa"
      #condition: event.payload.message == "aa" # postman
      #condition: event.payload.message > 3
