- name: say thanks
  hosts: localhost
  gather_facts: false
  tasks: 
    - debug:
        msg: "Thank you i am say-waht"
    # do a post request with message variable 
    - debug:
        msg: "I am variable message from eda original POST {{ event.payload.message }}"
    # do a post request with number variable 
    - debug:
        msg: "I am variable number from eda original POST {{ event.payload.number }}"