- name: say thanks
  hosts: localhost
  gather_facts: false
  tasks: 
    - debug:
        msg: "Thank you i am say-waht"
    - debug:
        msg: "Printing all the variable that was in payload that receveid EDA: {{ ansible_eda }}"
    # do a post request with message variable 
    - debug:
        msg: "message form eda {{ ansible_eda.event.payload.message  }}"
    - debug:
        msg: "message from numeber {{ ansible_eda.event.payload.number  }}"
    - debug:
        msg: "I am variable message from eda original POST {{ message_content }}"
    # do a post request with number variable 
    - debug:
        msg: "I am all the variables of the post payload {{ payload_content }}"